name: SpaceIsPlugin
version: '1.0'
api-version: 1.13
main: pl.spaceis.plugin.bukkit.BukkitSpaceIsPlugin
description: "Wykonuj komendy ze swojego sklepu SpaceIs"
website: https://spaceis.pl/
author: "Kamilkime"
