name: "SpaceIsPlugin"
version: "1.1"
api-version: "1.13"
main: "pl.spaceis.plugin.bukkit.BukkitSpaceIsPlugin"
description: "Wykonuj komendy ze swojego sklepu SpaceIs"
website: "https://spaceis.pl/"
authors: ["Kamilkime", "robalmeister"]

commands:
  spaceis:
    description: "Reload SpaceIsPlugin configuration"
    usage: "/spaceis reload"

permissions:
  spaceis.reload:
    default: "op"
