name: SpaceIs CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Git
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "SpaceIs CI"
          git config --global init.defaultBranch main
      - name: Grant execute permissions
        run: |
          chmod +x gradlew
      - name: Build spaceis-plugin JAR
        run: ./gradlew shadowJar --no-daemon